---
name: Upload python package

on:
  push:
    tags:
      - '[0-9]+.[0-9]+**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install poetry
      run: python -m pip install --upgrade pip poetry

    - name: Install packages
      run: poetry install

    - name: Build packages
      run: poetry build

    - name: Publish to pypi
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{secrets.PYPI_TOKEN}}
      run: poetry publish
